[package]
name = "zetamint"
version = "0.1.0"
description = "ZetaMint Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "zetamint"

[dependencies]
anchor-lang = "0.30.0"

[features]
no-entrypoint = []
